name: Hardened CI
on: 
  push:
    branches:
      - hardened-nginx-**
  pull_request:
    branches:
      - hardened-nginx-**
  release:
    types:
      - created
  workflow_dispatch: {}

permissions:
  contents: read

env:
  REGISTRY: rancher

jobs:
  unit:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    # Taken from the upstream ci.yaml action
    - name: Get go version
      run: echo "GOLANG_VERSION=$(cat GOLANG_VERSION)" >> $GITHUB_ENV

    - name: Set up Go
      id: go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: ${{ env.GOLANG_VERSION }}
        check-latest: true

    - name: Run Unit Tests
      run: ./scripts/test

  e2e:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Run E2E Tests
      # Runner user seems to lack permissions to access the kubeconfig file
      run: |
        SKIP_BUILDX_HACK=true ./scripts/e2e-test

  release:
    needs: e2e
    permissions:
      contents: read
      id-token: write # needed for the Vault authentication
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    
    # Only pull vault secrets if the repository is rancher
    - name: "Read secrets"
      if: github.repository_owner == 'rancher'
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials username | DOCKER_USERNAME ;
          secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials password | DOCKER_TOKEN

    - name: Login to Container Registry with Rancher Secrets
      if: github.repository_owner == 'rancher'
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_TOKEN }}

    - name: Build and push base image
      uses: rancher/ecm-distro-tools/actions/publish-image@master
      if: github.event_name == 'release' && github.event.action == 'created'
      env:
        REGISTRY: ${{ env.REGISTRY }}
      with:
        image: nginx-1.25
        tag: ${{ github.event.release.tag_name }}
        public-repo: rancher
        public-username: ${{ env.DOCKER_USERNAME }}
        public-password: ${{ env.DOCKER_PASSWORD }}
        push-to-prime: false
        make-target: push-image-nginx-1-25


    - name: Build and push Nginx Controller
      uses: rancher/ecm-distro-tools/actions/publish-image@master
      if: github.event_name == 'release' && github.event.action == 'created'
      env:
        REGISTRY: ${{ env.REGISTRY }}
      with:
        image: nginx-ingress-controller
        tag: ${{ github.event.release.tag_name }}
        public-repo: rancher
        public-username: ${{ env.DOCKER_USERNAME }}
        public-password: ${{ env.DOCKER_PASSWORD }}
        push-to-prime: false

    - name: Build and push Nginx Controller CHRoot
      uses: rancher/ecm-distro-tools/actions/publish-image@master
      if: github.event_name == 'release' && github.event.action == 'created'
      env:
        REGISTRY: ${{ env.REGISTRY }}
      with:
        image: nginx-ingress-controller-chroot
        tag: ${{ github.event.release.tag_name }}
        public-repo: rancher
        public-username: ${{ env.DOCKER_USERNAME }}
        public-password: ${{ env.DOCKER_PASSWORD }}
        push-to-prime: false
        make-target: push-image-chroot
